version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/sunny-strategy-364005/my-backend:1.2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    # ports:
    #   - 3000:3000

  # my-database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myprod09'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306