# 컴퓨터 만드는 설명서

# 1. 운영체제 설치( node 14버전과 npm과 yarn이 모두 설치되어있는 리눅스)
FROM node:14

# 3. 내 컴퓨터에 있는 폴더나 파일을 도커 컴퓨터 안으로 복사하기
COPY ./index.js /

# 4. 도커 안에서 index.js 실행시키기
CMD node index.js
# cmd는 한번밖에 못씀

# build를 통해 이미지 만들기
# 이미지 목록을 확인하기
# 확인한 이미지를 실행시켜보기